[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 8080
  port = 3000
  publish = "dist"
  autoLaunch = false